# Excercise 15 : Cows And Bulls
'''Create a program that will play the “cows and bulls” game with the user. 
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” 
Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.'''

'''from random import randint
num = randint(1,9999)
print("Hackers get %d" % num)
num_list = [int(x) for x in str(num)]
print("Welcome to the Cows and Bulls Game!")
guess = input("Enter a number : ")
guess_list = [int(x) for x in guess]
cows = 0
bulls = 0
for n in num_list:
    for g in guess_list:
        if (n==g and num_list.index(n) == guess_list.index(g)):
            cows = cows + 1
print("{0} cows, {1} bulls".format(cows, bulls))'''